feat(plugin-input-fields): add checkbox, experiment, select and textarea
AqueductHub/aqueductcore pull request #115
Opened 2024-05-15 08:59 UTC by jatinriverlane

## Changes

2024-05-22 15:08 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/CheckboxField/index.tsx
> +}
I guess we can also use the same pattern here.
```suggestion
interface CheckboxProps extends PluginFieldBase{
  defaultValue?: string;
}
```

2024-05-22 15:30 UTC, safeamiiir requested changes

2024-05-22 15:30 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/FileField/index.tsx
> +export function FileField({
In this component by just passing this props
```JSX
    <FileField
        title="test"
        field="test"
        options={['1', '2']}
        description="test"
    />
```
I received this error
```error
Cannot read properties of null (reading 'focus')
```

2024-05-22 15:30 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/TextAreaField/index.tsx
> +  border-color: ${({ theme }) => theme.palette.neutral.main};
This is not dark theme friendly, can you please also check others?

2024-05-22 15:30 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/NumberField/index.tsx
> +export function NumberField({
Have you also handle INT and FLOAT difference here?

2024-05-22 15:30 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/sharedStyledComponents/index.tsx
I still think it's a better idea to keep these in sepatated file, or if you think it's bette to have them in one place, maybe something like `sharedStyledComponents/InputFields/index.tsx`?

2024-05-22 15:30 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/CheckboxField/index.tsx
> +  defaultValue = ""
We can make consider them optional and keep empty string as default value, or if they're required no for the default value. By changing the type above I guess it mostly will be fixed, just we need to decide for `defaultValue` prop.

2024-05-22 15:30 UTC, safeamiiir commented on aqueductcore/frontend/src/components/atoms/ExperimentField/index.tsx
> +  description = "",
Same for default values or making them optional in type

2024-05-22 16:04 UTC, jatinriverlane commented on aqueductcore/frontend/src/components/atoms/CheckboxField/index.tsx
> +}
Yeah, missed this.

2024-05-23 10:40 UTC, jatinriverlane commented on aqueductcore/frontend/src/components/atoms/CheckboxField/index.tsx
> +  defaultValue = ""
Thanks @safeamiiir for help on this

2024-05-23 16:41 UTC, safeamiiir approved these changes

2024-05-24 09:13 UTC, merged