feat(automatic-release): Automated release for aqueduct core
AqueductHub/aqueductcore pull request #118
Opened 2024-05-20 16:00 UTC by jatinriverlane

# Changes
* update trigger from workflow dispatch to cron
* add condition of deployment to confirm with the environment variable of ALLOW_AUTOMATED_RELEASE
* add generateReleaseNotes as True to automatically add release notes

2024-05-21 13:22 UTC, samiralavi requested changes
Generally looks good but there are points to improve.

2024-05-21 13:22 UTC, samiralavi commented on .github/workflows/release.yaml
> -  workflow_dispatch:
Please make sure the `workflow_dispatch` is there. We might want to still release manually instead of waiting for two weeks.

2024-05-21 13:22 UTC, samiralavi commented on .github/workflows/release.yaml
> +    if: ${{ env.ALLOW_AUTOMATED_RELEASE == 'true' }}
You need to add a condition for the manual trigger to bypass this.

2024-05-21 13:22 UTC, samiralavi commented on .github/workflows/release.yaml
> +        if: ${{ steps.is_release_allowed_check.outputs.is_release_allowed }}
Instead of adding this check to every task of the `build` job, you can create a new job before `build` and make sure the `build` depends on the job. If the job gets then the dependant jobs don't get executed. Think of it like a pipeline.

2024-05-21 13:22 UTC, samiralavi commented on .github/workflows/release.yaml
> -  workflow_dispatch:
This also helps us to change the major and minor version numbers ourselves, but let the CI increment only the patch version.

2024-05-21 13:22 UTC, samiralavi commented on .github/workflows/release.yaml
> +        run: ci/build_docker_image.sh -i aqueductcore -p true -t ${{ steps.next_version.outputs.version }}
for testing purposes, I recommend changing this to `aqueductcore-dev` until you made sure everything is working fine.

2024-05-21 13:28 UTC, jatinriverlane commented on .github/workflows/release.yaml
> -  workflow_dispatch:
@samiralavi Shouldn't we have different workflows for `automatic release triggered by cron having no input` and `manual release triggered manually with version input`. Although having different workflows will have some code duplication, but we won't have to apply multiple if else conditions in case of single workflow. Having them differently will be less error prone as well. 

What are your views on this ?

2024-05-23 10:59 UTC, samiralavi approved these changes
Thanks @jatinriverlane, this is what I call a clean approach.

2024-05-28 13:43 UTC, safeamiiir approved these changes
Thanks Jatin!

I checked the ncipollo/release-action and it'll fail if we don't have changes from the previous release based on `allowUpdates` input and by default it's false and it'll fail the release if it already exists.

2024-06-09 14:14 UTC, merged