docs(plugins): adding server documentation for plugins
AqueductHub/aqueductcore pull request #122
Opened 2024-05-22 11:43 UTC by str-anger

This pull request addresses documentation of plugin creation and installation and finalises necessary changes for plugin installation.

2024-05-24 10:15 UTC, gabrielg42 requested changes
Thanks Stas! I left comments concerning some details and some English. Great summary otherwise!

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +   2. Conditional. If `pyproject.toml` file is present, folder content is installed as a python module in the new virtual environment together with its dependencies.
```suggestion
2. Conditional: If inside the plugin folder python virtual environment is not present, it will be created.
   1. Conditional: If `requirements.txt` file is present, dependencies are installed in the new virtual environment.
   2. Conditional: If `pyproject.toml` file is present, folder content is installed as a python module in the new virtual environment together with its dependencies.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +   2. Conditional. If `pyproject.toml` file is present, folder content is installed as a python module in the new virtual environment together with its dependencies.
Silly question: if Python is not needed by the plugin, will the virtual environment be created? I guess not, no?

Maybe we can say something like, 
> If a plugin requires a Python virtual environment (indicated by the use of `$python` in the `manifest.yml`) and it is not present, one will be created.

Is this the behavior that exists now?

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +subfolder to enforce virtual environment re-creation.
```suggestion
subfolder to force virtual environment re-creation.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +Unpack a plugin folder into a host folder, and the container will immediately see the changes.
```suggestion
Plugins are folders which could be distributed in the form of archives. When starting the server using Docker, 
bind mount a host folder to the Aqueduct container at `/workspace/plugins`.
Unpack a plugin folder into the host folder, and the container will immediately see the changes.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +For examples, you map host folder `/usr/data/plugins` to `/workspace/plugins`, and then `/usr/data/plugins/dummy/manifest.yml` with become available inside a container as `/workspace/plugins/dummy/ma
```suggestion
For example, if you map host folder `/usr/data/plugins` to `/workspace/plugins`, 
then `/usr/data/plugins/dummy/manifest.yml` within will become available inside the container as `/workspace/plugins/dummy/manifest.yml`.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +* Function parameters are allowed to have `select` type. If necessary, update `options` list for such fields with respect configuration needs.
```suggestion
* Function parameters are allowed to have `select` type. If necessary, update `options` list for such fields with respect to your configuration needs.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +or binary architecture is supported by an executing machine.
```suggestion
or binary architecture is supported by the executing (virtual) machine.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +Current implementation of plugins run their code at the aqueduct server machine
```suggestion
In the current implementation of plugins, their code is run on the Aqueduct server machine 
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +Technically, plugins are folders with files, which follow a plugin convention.
```suggestion
Technically, plugins are folders with files which follow a plugin convention.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +`authors`). This information is used to generate user interface.
```suggestion
`authors`). This information is used to generate the user interface.
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +`aqueduct_url` mandatory parameter is used to make plugin aware about the instance of Aqueduct
```suggestion
The `aqueduct_url` mandatory parameter is used to make the plugin aware of the instance of Aqueduct
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +it should interact with. In current implementation plugins assumed to run at the same machine
```suggestion
it should interact with. In the current implementation, plugins are assumed to run on the same machine 
```

2024-05-24 10:15 UTC, gabrielg42 commented on docs/plugins.md
> +this purpose.
```suggestion
Optional `params` section allows the defintion key-value pairs for constants shared across all plugin function executions. 
Examples of this may include third-party service credentials, or a database connection string,
which are shared among all service installation users. If your users need to use such services
with different credentials, we encourage you to define a separate function parameter for 
this purpose.
```

2024-05-24 10:15 UTC, gabrielg42 commented on README.md
> +        source: /aqueductcore/plugins
```suggestion
        source: aqueductcore/plugins
```
Does there need to be a slash here?

2024-05-24 11:45 UTC, str-anger commented on scripts/release/docker-compose.yaml
> +    platform: linux/amd64
I think this makes this just more compatible. Base images are ubuntu, only supported architecture is x86_64. Which make explicit specification just a declaration of de facto state. And yes, this declaration allows to run things on apple silicon.

@samiralavi your opinion on this flag?

2024-05-24 11:47 UTC, str-anger commented on docs/plugins.md
> +   2. Conditional. If `pyproject.toml` file is present, folder content is installed as a python module in the new virtual environment together with its dependencies.
venv is created any way. Probably, this maybe stated clearer in the text.

2024-05-24 11:49 UTC, str-anger commented on docs/plugins.md
> +## Writing Plugin Code
Nnnnno. Probably good idea to align.

2024-05-24 13:33 UTC, gabrielg42 approved these changes

2024-05-28 17:07 UTC, safeamiiir approved these changes
Thanks Stas!

2024-05-28 17:07 UTC, safeamiiir commented on docs/extensions.md
> +```
I was wondering maybe we can show it this way:
```suggestion
```yaml
      - 
        name: parameter_name
        description: text, used in the interface to explain the value
        # one of str|textarea|file|experiment|int|float|select|bool
        data_type: str
        # optional
        default_value: optional field, populates the field by default
        # optional, used with "select" type
        options: value 1, value 2, value 3, value 4
```
| Name           | parameter_name                                                        |
|----------------|------------------------------------------------------------------------|
| Description    | `text`, used in the interface to explain the value                       |
| Data Type      |  `str` \| `textarea` \| `file` \| `experiment` \| `int` \| `float` \| `select` \| `bool` |
| Default Value  (optional) |  `text`, populates the field by default                         |
| Options        | `text[]` value 1, value 2, value 3, value 4                                     |
```

2024-05-28 17:09 UTC, safeamiiir requested changes
Some changes requested.

2024-05-28 17:11 UTC, safeamiiir requested changes
Thanks Stas! some changes requested.

2024-06-04 08:49 UTC, samiralavi commented
Could you please merge main into your branch to have the docs preview feature for this PR?

2024-06-04 08:51 UTC, str-anger commented on docs/extensions.md
> +Technically, extensions are folders with files which follow an extension convention.
I feel like people who ask this question (and answer in StackOverflow) pay too much attention to the common concept with obviously synonymic names. But I agree it is easy to be consistent.

2024-06-04 10:23 UTC, safeamiiir commented on docs/extensions.md
> +Technically, extensions are folders with files which follow an extension convention.
Yeah it's not to say one is right or the other just to keep it mostly consistent during the docs

2024-06-05 11:11 UTC, merged