feat(plugin-mocks): Added mocks for getAllPlugins query
AqueductHub/aqueductcore pull request #132
Opened 2024-05-24 14:09 UTC by jatinriverlane

## Changes:
* add mocks for getAllPlugins query

2024-05-29 09:49 UTC, samiralavi approved these changes

2024-06-04 17:12 UTC, str-anger requested changes
I feel like my skills don't allow me to judge the code, but for the naming, please in the commented places and everywhere else try to use `(extensions, actions)` convention.

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/API/graphql/queries/getAllExtentions.tsx
> +  query getAllPlugins {
```suggestion
  query getAllExtensions {
```

I hope this well be merged soon: https://github.com/AqueductHub/aqueductcore/blob/a356e0c8f5ea11eef572cd88ee8d5a245424a4df/aqueductcore/backend/routers/graphql/query_schema.py#L107

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/API/graphql/queries/getAllExtentions.tsx
> +        parameters {
```suggestion
    extensions {
      authors
      description
      actions {
        description
        experimentVariableName
        name
        parameters {
```

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/__mocks__/queries/getAllExtentionsMock.tsx
> +          "plugins": [
```suggestion
          "extensions": [
```

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/__mocks__/queries/getAllExtentionsMock.tsx
> +              "functions": [
```suggestion
              "actions": [
```

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/__mocks__/queries/getAllExtentionsMock.tsx
> +              "functions": [
```suggestion
              "actions": [
```

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/types/globalTypes.ts
> +  PluginInfo,
```suggestion
  ExtensionExecutionResult,
  ExtensionActionInfo,
  ExperimentData,
  ExperimentFile,
  Experiments,
  ExtensionInfo,
```

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/types/globalTypes.ts
> +  MutationExecutePluginArgs,
```suggestion
  MutationExecuteExtensionArgs,
```

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/types/globalTypes.ts
> +export type GET_ALL_EXTENSIONS_TYPE = {
here as well. Let us stick to extensions and actions.

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/types/globalTypes.ts
> +export type PluginFunctionInfoType = {
extensions, actions

2024-06-04 17:12 UTC, str-anger commented on aqueductcore/frontend/src/types/globalTypes.ts
> +//############### Plugin types ###############//
```suggestion
//############### Extension types ###############//
```

2024-06-12 09:20 UTC, jatinriverlane commented
This has been implemented in a different PR

2024-06-12 09:20 UTC, closed without merging