feat(enhanced-extension): add validation and dark theme support to extension modal
AqueductHub/aqueductcore pull request #153
Opened 2024-06-13 13:47 UTC by jatinriverlane

## Changes
* Add field hints to show type of data to be filled.
* Disabling RUN EXTENSION button till the required fields are not filled.
* Fix dark mode failures in extension modal.

2024-06-19 12:46 UTC, samiralavi approved these changes

2024-06-19 17:13 UTC, safeamiiir requested changes

2024-06-19 17:13 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
> +
we can replace it all with this variable
```suggestion
    const isExtensionExexutable = inputParams?.every(param => param.value)
```

2024-06-19 17:13 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
> +    const [executeExtensionEnabled, setExecuteExtensionEnabled] = useState(false);
This line also will be removed

2024-06-19 17:13 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
> +                                disabled={!executeExtensionEnabled}
And 
```suggestion
                                disabled={!isExtensionExexutable}
```

2024-06-20 14:19 UTC, safeamiiir approved these changes

2024-06-20 14:24 UTC, merged