Fix/rename id alias frontend
AqueductHub/aqueductcore pull request #155
Opened 2024-06-14 16:38 UTC by safeamiiir

Frontend renaming

2024-06-17 13:51 UTC, str-anger requested changes
Probably may become better with some minor changes.

2024-06-17 15:19 UTC, safeamiiir commented on aqueductcore/frontend/src/__mocks__/queries/experiment/getExperimentFilesById.tsx
> +import { ExperimentsDataMock, eid } from "__mocks__/ExperimentsDataMock";
No it's a sample for `eid` I've changed it into `sample_eid`

2024-06-17 15:20 UTC, safeamiiir commented
Thanks @str-anger for all better naming! 😁

2024-06-18 09:55 UTC, str-anger approved these changes
Good to go!

2024-06-18 11:09 UTC, merged