feat(api)!: API enchancement
AqueductHub/aqueductcore pull request #164
Opened 2024-06-19 13:14 UTC by samiralavi

This PR is a for the renaming in the API to rename `alias` to `eid` and `id` to `uuid` for experiments.

2024-06-20 14:03 UTC, jatinriverlane approved these changes
Thanks @samiralavi

2024-06-21 09:37 UTC, str-anger requested changes
A minor change requested -- you've added an extension file, probably accidentaly.

2024-06-21 09:37 UTC, str-anger commented on aqueductcore/frontend/src/components/organisms/ExperimentDetailsActionButtons/index.tsx
> +                        title="toggle-favourite"
What is this? =)

2024-06-21 09:37 UTC, str-anger commented on extensions/python-example/solve_alpha.py
> +import os
Extensions are deleted and moved to `external/extensions` as a submodule

2024-06-21 12:25 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/ExperimentDetailsActionButtons/index.tsx
> +                        title="toggle-favourite"
It's a title which is used in tests

2024-06-24 09:16 UTC, safeamiiir approved these changes

2024-06-24 14:04 UTC, samiralavi commented on extensions/python-example/solve_alpha.py
> +import os
I have removed it.

2024-06-24 15:04 UTC, str-anger approved these changes

2024-06-24 19:21 UTC, merged