feat(ci): Add automated changelog workflows to repo
AqueductHub/aqueductcore pull request #175
Opened 2024-07-01 14:29 UTC by samiralavi

2024-07-01 14:42 UTC, samiralavi commented
@safeamiiir should I create new labels on the repo based on the default ones mentioned here?

2024-07-03 09:20 UTC, safeamiiir requested changes

2024-07-03 09:20 UTC, safeamiiir commented on .github/workflows/changelog.yml
Can we run this workflow after each release instead of each PR into main?

2024-07-03 12:21 UTC, samiralavi commented on .github/workflows/changelog.yml
You are right, running it after every commit is overkill. I am going to use a different github action to only add items when we release.

2024-07-04 09:45 UTC, str-anger approved these changes

2024-07-12 09:39 UTC, jatinriverlane reviewed
Thanks @samiralavi

2024-07-12 09:40 UTC, jatinriverlane approved these changes

2024-07-18 13:40 UTC, str-anger approved these changes

2024-07-18 13:43 UTC, samiralavi commented
@safeamiiir I have made the changes to generate and commit the changelog only on release. It creates there categories for breaking changes, new features and fixes so anyone can easily find the changes.

2024-07-24 09:29 UTC, safeamiiir approved these changes
Nice and simple!
Thanks

2024-07-24 09:58 UTC, merged