feat(remove-files): add router view for removing files
AqueductHub/aqueductcore pull request #186
Opened 2024-07-09 10:00 UTC by jatinriverlane

## Changes
* add router view for removing files from the experiment

2024-07-10 12:19 UTC, str-anger requested changes

2024-07-10 12:19 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +        await get_experiment_by_uuid(
Is this not accepting a result for a reason?

2024-07-10 12:19 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +async def remove_experiment_file(
May I ask you to separate router function and actual business logic (file deletion). It will probably sit nice in `Experiment.remove_file(filename)` method.

2024-07-10 15:24 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +        await get_experiment_by_uuid(
It's not accepting any result, this is just a validation. It checks if experiment with the given UUID is present or not. If it does not exist, it raises an exception from Line 270.

2024-07-11 09:25 UTC, str-anger requested changes

2024-07-11 09:25 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +
```suggestion

# check the experiment exists before deleting a file from it
```

2024-07-11 09:25 UTC, str-anger commented on aqueductcore/backend/services/utils.py
> +def arr_humanize(arr: list[str | int]) -> str:
test on this, please?

2024-07-11 09:25 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +async def remove_experiment_files(
I will copy my comments from the previous review, as it was not addressed.

May I ask you to separate router function and actual business logic (file deletion). It will probably sit nice in `Experiment.remove_file(filename)` method?

2024-07-11 09:25 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +async def remove_experiment_files(
And then - a test please.

2024-07-11 17:50 UTC, jatinriverlane commented on aqueductcore/backend/services/utils.py
> +def arr_humanize(arr: list[str | int]) -> str:
Have added test for this

2024-07-12 15:12 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +async def remove_experiment_files(
The structure of the file based features are monolithic functions. The upload_file and download_file as also in the same pattern. For refactoring, we can divide the functions in this file to multiple smaller blocks. I guess it can be picked in a different PR.

2024-07-15 09:19 UTC, samiralavi approved these changes
Thanks @jatinriverlane, the logic is fine. Could you please re-evaluate to implement the functionality as a GraphQL mutation instead of a new REST API? As we discussed, we only use REST API only for file upload and download as an exception as the GraphQL library didn't expose file streaming. If it is something that can be done quickly, I suggest doing it now, otherwise, we can later refactor it.

2024-07-15 09:19 UTC, samiralavi commented on aqueductcore/backend/routers/files.py
> +    return JSONResponse({"result": f"Successfully deleted {arr_humanize(file_list)}"})
Does this really need its own utility function if it is only used once? Also, the function name is not clear.

2024-07-15 12:06 UTC, samiralavi requested changes
Thanks @jatinriverlane. I have requested changes to the API contract and how it should be called. Also, a new user scope for file deletion is needed as this is a critical operation that should be secured.

2024-07-15 12:06 UTC, samiralavi commented on aqueductcore/backend/routers/files.py
> +@router.delete("/{experiment_uuid}")
If you want to stick to REST contract, I suggest using DELETE operation with `"/{experiment_uuid}/{file_name}"` for single file deletion. If you want multiple files deletion in one call, change it to POST, as it is not a common practice to add data to the request body with DELETE verb.

2024-07-15 12:06 UTC, samiralavi commented on aqueductcore/backend/routers/files.py
> +    if not file_list:
Please make sure this operation is secured by a specific user scope and the user scope should be checked for that.

2024-07-15 15:35 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +@router.delete("/{experiment_uuid}")
I agree, as we wish to support multiple file deletion in a single request, this is updated to being a POST request with the file list in the request body.

2024-07-15 15:36 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    return JSONResponse({"result": f"Successfully deleted {arr_humanize(file_list)}"})
This is used at 2 places. However, the name is not appropriate. The name of this utility function is now converted to `format_list_human_readable`

2024-07-15 19:25 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    if not file_list:
Sure @samiralavi , have added user scope check

2024-07-16 09:49 UTC, samiralavi requested changes
Thanks @jatinriverlane. I am happy with the changes except the way you are handling request body. I have put the a comment to refactor using FastAPI models.

2024-07-16 09:49 UTC, samiralavi commented on aqueductcore/backend/routers/files.py
> +    request_body = await request.json()
FastAPI already provides a safe way to get arguments with type validation. Please rewrite that using that functionality:
https://fastapi.tiangolo.com/tutorial/body-fields/

2024-07-16 14:29 UTC, safeamiiir approved these changes

2024-07-16 14:29 UTC, safeamiiir commented on aqueductcore/backend/routers/files.py
> +            detail="File list is missing from the request body."
I was wondering maybe we should have a different error message compared to `400`
```suggestion
            detail="File list can not be empty"
```

2024-07-16 14:29 UTC, safeamiiir commented on aqueductcore/backend/routers/files.py
> +                )
Don't you agree we can do this logic in a function?
something like what we have in the frontend `isUserAbleToDeleteExperiment`

2024-07-16 14:29 UTC, safeamiiir commented on aqueductcore/backend/routers/files.py
> +                detail=f"File {file_name} is invalid !"
```suggestion
                detail=f"File {file_name} is invalid!"
```

2024-07-16 14:50 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +                )
@safeamiiir This block is used only once in Aqueduct backend. I guess it'll better to convert it to a function once we have more than one usage of such block.

2024-07-16 16:58 UTC, str-anger requested changes

2024-07-16 16:58 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +async def remove_experiment_files(
I don't feel like "other functions are already monolithic" is a valid excuse for not stopping doing this =)

2024-07-16 16:58 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +    file_list = file_list.file_list
1. I see duplication with 189....

2024-07-16 17:20 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    file_list = file_list.file_list
@str-anger Actually, feat/remove-experiment-file-frontend was branched off from this branch only. Because of that, the changes are visible in both PRs.

2024-07-17 12:58 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +async def remove_experiment_files(
As discussed, this will be picked in a different PR...

2024-07-17 14:16 UTC, samiralavi approved these changes
Thanks @jatinriverlane for the changes.

2024-07-17 14:46 UTC, merged