feat(delete-file-frontend): Functionality to delete files from experiment
AqueductHub/aqueductcore pull request #189
Opened 2024-07-14 10:32 UTC by jatinriverlane

## Changes
* add delete file function
* add delete file from experiment button
* add relevant tests for delete file functionality

2024-07-16 16:55 UTC, str-anger requested changes
Some changes may probably make it better!

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/context.py
> +class FileList(BaseModel):
What stops us from using `List[str]` instead? This wrapper brings no additional capabilities.

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +    file_list: FileList
```suggestion
    file_list: List[str]
```

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +    file_list = file_list.file_list
... Especially if you have this line. This changes type of the file_list object (was FileList, became List[str])

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +    if not file_list:
This line also triggers for `None`.

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +    if file_list is None:
This is impossible, if you did not make the list optional.

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +                    "The user doesn't have permission to delete files from this experiment."
Should we add user name as well to the message?

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +        dest_file_path = os.path.join(experiment_dir, file_name)
Is this outside the loop? files name is the variable name from the loop on line 268
Looks like `for` is missing

2024-07-16 16:55 UTC, str-anger commented on aqueductcore/backend/routers/files.py
> +            os.remove(dest_file_path)
Am I right this is a second-time validation for the case of parallel competing process doing the same? I'd probably let it fail without re-check.

2024-07-16 16:55 UTC, str-anger commented on tests/unittests/test_files.py
> +    assert response.json() == {"detail": f"File(s) not found - {non_existing_file}"}
1. May you please add/edit tests to capture all exceptional situations?
2. Also, probably handle
  a. longer-than 1 list
  b. partial matches
  c. a folder instead of the file

2024-07-16 17:00 UTC, jatinriverlane commented on aqueductcore/backend/context.py
> +class FileList(BaseModel):
@str-anger https://fastapi.tiangolo.com/tutorial/body-fields/ mentions the recommended way of parsing request body as a pydantic model. Hence, we are using this.

2024-07-16 17:01 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    file_list: FileList
@str-anger An alternate change for this would be to set the name of parameter to be something similar to request_body.

2024-07-16 17:02 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    file_list = file_list.file_list
Having request body as parameter name would make it favourable to use
```python
file_list = request_body.file_list
```

2024-07-16 17:06 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    if not file_list:
So, if `file_list` is None, pydantic will return error by itself, with status code 422.

i.e. in case `file_list` is `None`, code will not reach this point. This is handling just the case for empty `file_list` array.

2024-07-16 17:07 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +    if file_list is None:
Right @str-anger , I'll remove this block.

2024-07-16 17:12 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +                    "The user doesn't have permission to delete files from this experiment."
In other APIs, we haven't mentioned the username in the error message. Having such error just makes it similar to other responses. For eg.
* The user doesn't have the permission to remove the experiment.
* The user doesn't have the required permission(s) to create experiments.

However, it's easy to include username in error message. Do you suggest that we should add username ?

2024-07-16 17:28 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +            os.remove(dest_file_path)
Right, there's no need to validate during the delete operation. Just the initial validation is fine.

2024-07-16 17:30 UTC, jatinriverlane commented on aqueductcore/backend/routers/files.py
> +        dest_file_path = os.path.join(experiment_dir, file_name)
🤦‍♂️ Slipped my mind. Have fixed this now in the backend PR https://github.com/AqueductHub/aqueductcore/pull/186

2024-07-16 17:59 UTC, jatinriverlane commented on tests/unittests/test_files.py
> +    assert response.json() == {"detail": f"File(s) not found - {non_existing_file}"}
Sure, I've implemented `longer-than 1 list` and `partial matches` tests. I'm thinking about other tests that can be created for this. 

But, I don't see `folder instead of the file` happening in real life.

2024-07-17 14:19 UTC, samiralavi approved these changes
I have already reviewed and approved the backend changes in the previous PR. I approve here the frontend changes, but please make sure @safeamiiir reviews this as he has the the FE knowledge the same as you.

2024-07-17 14:19 UTC, samiralavi commented on aqueductcore/backend/context.py
> +class FileList(BaseModel):
@jatinriverlane does this need to be in the `context.py` module?

2024-07-17 14:40 UTC, jatinriverlane commented on aqueductcore/backend/context.py
> +class FileList(BaseModel):
@samiralavi As discussed, I've moved it to `backend/routers/files.py`

2024-07-23 15:36 UTC, safeamiiir approved these changes
Thank you Jatin!
I just added a suggestion on delete button behaviour.

2024-07-23 15:36 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/Attachments/index.tsx
> +        </Grid>}
What do you think about keeping the Divider and disabling the delete button?

```jsx
        <Grid item>
          <Divider orientation="vertical" />
        </Grid>
        <Grid item>
          <BorderedButtonWithIcon
            variant="outlined"
            size="small"
            color="neutral"
            sx={{ ml: 0.5 }}
            onClick={handleOpenDeleteExperimentFileModal}
            startIcon={<DeleteOutlineOutlinedIcon />}
            disabled={!selectedFile}
          >
            Delete
          </BorderedButtonWithIcon>
          <DeleteExperimentFileModal
            open={isDeleteExperimentFileModalOpen}
            onClose={handleCloseDeleteExperimentFileModal}
            handleDeleteExperimentFile={handleFileDelete}
          />
        </Grid>
```

2024-07-23 16:54 UTC, jatinriverlane commented on aqueductcore/frontend/src/components/organisms/Attachments/index.tsx
> +        </Grid>}
🤔 The current behaviour seems to be fine. Showing a disabled button when no file is selected might be confusing. A disabled button might show that the button is not functional.

2024-07-24 09:11 UTC, safeamiiir approved these changes
Thanks!

2024-07-24 09:40 UTC, str-anger commented on tests/unittests/test_files.py
> +    assert response.status_code == status.HTTP_400_BAD_REQUEST
I'd say that 400 is generic and correct, but may be confused with just a messy input. What about 409, 417? https://umbraco.com/knowledge-base/http-status-codes/

2024-07-24 15:57 UTC, jatinriverlane commented on tests/unittests/test_files.py
> +    assert response.status_code == status.HTTP_400_BAD_REQUEST
@str-anger These status codes seems to be related to request headers and server states. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

400 seems to be the better option. You can read from the above link, it has more explanation for this.

2024-07-24 16:00 UTC, str-anger commented on tests/unittests/test_files.py
> +    assert response.status_code == status.HTTP_400_BAD_REQUEST
409 looks reasonable: 
> [409 Conflict](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409)
This response is sent when a request conflicts with the current state of the server.

2024-07-25 12:12 UTC, jatinriverlane commented on tests/unittests/test_files.py
> +    assert response.status_code == status.HTTP_400_BAD_REQUEST
Sure, 409 seems to be the right status code for this case. Thanks @str-anger

2024-07-25 12:20 UTC, jatinriverlane commented on aqueductcore/frontend/src/components/organisms/Attachments/index.tsx
> +        </Grid>}
@safeamiiir As Tom suggested, I've implemented your suggestion to enable /disable Delete button based on file selection

2024-07-25 13:25 UTC, merged