feat(jobs-api): adding mock API calls for jobs listing and status check
AqueductHub/aqueductcore pull request #199
Opened 2024-08-01 17:30 UTC by str-anger

--

2024-08-02 11:43 UTC, safeamiiir requested changes

2024-08-02 11:43 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/types.py
> +    SUCCESS = "success"
Are these Flower API states? if yes we can have them like as they are and later in the frontend they will be labeled as it's in the design.

2024-08-02 11:43 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/query_schema.py
> +            ),
Why do we want to do this conversion in the server?
We can have this inexpensive computation in the frontend and it's easier to be converted based on the design in different places.
time in seconds should be fine.

2024-08-02 11:43 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/inputs.py
> +class TasksFilterInput:
This change does help with the experiment details page design, well done Stas!

2024-08-02 11:43 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/types.py
> +    eid: str = strawberry.field(description="Experiment the task is associated with.")
Not sure if it's a good practice in GraphQL or not, but can we enable this query being able to ask for more info on the experiment just here?

it saves one more request in the frontend, and we have the experiment object here already.

like:
```
experiment {
  uuid
  eid
  title
  ...
}
```

2024-08-02 11:50 UTC, samiralavi requested changes
Good work @str-anger, I requested a few changes to the naming convention.

2024-08-02 11:50 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/inputs.py
> +    author_name: Optional[str] = None
`author` is a new keyword that we have not used so far, let's user `username` instead which we already have

2024-08-02 11:50 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/inputs.py
> +    experiment_id: Optional[str] = None
We have an `ExperimentIdentifierInput` type, replace `str` with it.

2024-08-02 11:50 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/query_schema.py
> +    async def task_status(
For coherency, please follow the naming style we implemented for experiments and change it to `task`.

2024-08-02 11:50 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/query_schema.py
> +    async def task_runs(
For coherency, please follow the naming style we implemented for experiments and change it to `tasks`.

2024-08-02 11:50 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/types.py
> +    author: Optional[str] = strawberry.field(description="User, who stated the task.")
`user` or `username`

2024-08-02 11:56 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/inputs.py
> +class TasksFilterInput:
How about having action_name as well in filter to allow users to narrow down the list more

2024-08-02 12:03 UTC, str-anger commented on aqueductcore/backend/routers/graphql/query_schema.py
> +            ),
As you wish =)

2024-08-02 12:03 UTC, str-anger commented on aqueductcore/backend/routers/graphql/types.py
> +    SUCCESS = "success"
These are from requirements. @jatinriverlane are they Celery statuses?

2024-08-02 13:41 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/types.py
> +    eid: str = strawberry.field(description="Experiment the task is associated with.")
I was reading about it and realised the [nesting](https://docs.github.com/en/graphql/guides/migrating-from-rest-to-graphql#example-nesting) is the better way with GraphQL. It's more aligned with its philosophy to "ask for what you need".

2024-08-02 13:50 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/types.py
> +    SUCCESS = "success"
Flower just sends the states as received from Celery. i.e. Yes, they are Celery statuses.

2024-08-02 14:32 UTC, jatinriverlane approved these changes
Thanks @str-anger

2024-08-02 14:34 UTC, safeamiiir approved these changes

2024-08-05 12:44 UTC, samiralavi approved these changes

2024-08-05 12:54 UTC, merged