Feat/tt 93 job details
AqueductHub/aqueductcore pull request #205
Opened 2024-08-12 15:55 UTC by jatinriverlane

2024-08-14 09:24 UTC, samiralavi approved these changes
All looks good to me, good work @jatinriverlane

2024-08-16 12:33 UTC, safeamiiir requested changes

2024-08-16 12:33 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/JobsListTable/index.tsx
> +import JobDetailsModal from "../JobDetailsModal";
```suggestion
import JobDetailsModal from "components/organisms/JobDetailsModal";
```

2024-08-16 12:33 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/JobsListTable/index.tsx
> -                                        // !TODO: after TT-122 is completed
Let's still keep this one comment

2024-08-16 12:33 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/JobDetailsModal/index.tsx
> +                setInputParams={() => {}}
This line is extra.
We can make the `ActionParameters/>` component props conditional using [this approach](https://stackoverflow.com/a/75433249/10597542).
We only need to have `setInputParams ` if it's not readonly.

2024-08-16 12:33 UTC, safeamiiir commented on aqueductcore/frontend/src/components/molecules/LogsViewer/index.tsx
Sorry for being pedantic.
I feel like this is a `LogViewer` actually not _logs_. I might be wrong as a non-native speaker, but my understanding it that logs is a list the includes several log, but here we just do log to single run.

2024-08-16 12:33 UTC, safeamiiir commented on aqueductcore/frontend/src/components/molecules/LogsViewer/index.tsx
> +    font-size: 0.813rem;
As a general comment, I guess these `font-size` are coming from Figma? let's ignore it with _this precision_, if it's really annoying in the design we can do `0.8` maybe? or the better approach is to use font-size as css-var.

2024-08-16 12:33 UTC, safeamiiir commented on aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
> +    line-height: 3.313rem;
same comment as i mentioned for `font-size` this precision is a bit unnecessary IMO.

2024-08-16 16:11 UTC, jatinriverlane commented on aqueductcore/frontend/src/components/organisms/JobsListTable/index.tsx
> -                                        // !TODO: after TT-122 is completed
Sure, adding this line again

2024-08-16 16:12 UTC, jatinriverlane commented on aqueductcore/frontend/src/components/organisms/JobsListTable/index.tsx
> +import JobDetailsModal from "../JobDetailsModal";
Done, updated

2024-08-19 14:52 UTC, safeamiiir approved these changes

2024-08-19 14:53 UTC, merged