feat(tasks)!: Support for tasks through GraphQL, service layer and database access layer
AqueductHub/aqueductcore pull request #207
Opened 2024-08-15 14:40 UTC by samiralavi

2024-08-19 12:53 UTC, jatinriverlane commented on aqueductcore/backend/models/task.py
> +    ended_at: Optional[datetime] = None
I guess we can also add `started_at` and other similar fields here, given that `ended_at` is currently present and not operational right now.

2024-08-19 12:55 UTC, jatinriverlane commented on aqueductcore/backend/models/task.py
> +class TaskCreate(TaskBase):
TaskCreate class inherits from TaskBase, but TaskBase has `std_err`, `std_out`, `result_code` and other similar fields. I think the fields can be redistributed among the `Create` and `Read` classes.

2024-08-19 13:55 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/types.py
> -    username: Optional[str] = strawberry.field(description="User, who stated the task.")
There's a requirement for username of User who executed the task. How will we get this data ?

2024-08-19 15:02 UTC, samiralavi commented on aqueductcore/backend/models/task.py
> +class TaskCreate(TaskBase):
It is possible to refactor as you suggested, I instead set some of the fields as optional, thought it was simpler.

2024-08-19 15:08 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/inputs.py
> +    params: List[List[str]]
`List[List[str]]` is also fine, we can also use list of dictionaries.

2024-08-19 15:15 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/mutations/task_mutations.py
> +    task = await ExtensionsExecutor.execute(
I guess it'd be a good idea to add a `try-catch` block here so that if anything happens during execution of `execute` function, it returns valid data to the User.

2024-08-19 15:15 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/mutations/task_mutations.py
> +    task = await ExtensionsExecutor.execute(
Similar handling can be added to `cancel_task` function as well.

2024-08-19 15:42 UTC, jatinriverlane commented on aqueductcore/backend/services/task_executor.py
> +    order_by_creation_date: bool = True,
This can be `order_by_creation_time`...

2024-08-19 15:44 UTC, jatinriverlane commented on aqueductcore/backend/services/task_executor.py
> +    AsyncResult(db_task.task_id).revoke(terminate=terminate, signal="SIGTERM")
🤔 Maybe we can add this call to a `try-catch` block to make sure that failure of `revoke` is handled.

2024-08-19 15:54 UTC, jatinriverlane requested changes
Great work @samiralavi , just a few comments from my side on this PR

2024-08-20 09:08 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/inputs.py
> +    params: List[List[str]]
I like to do that, I kept it as it was the contract before. @safeamiiir are you happy with this change in the graphql params input type?

2024-08-20 09:08 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/mutations/task_mutations.py
> +    task = await ExtensionsExecutor.execute(
Nice suggestion, I will go through them and try to add more exception handling

2024-08-20 09:09 UTC, samiralavi commented on aqueductcore/backend/services/task_executor.py
> +    order_by_creation_date: bool = True,
I followed the same naming we did for experiments, so either I have to change that, or keep it coherent. I prefer to keep it as it is.

2024-08-20 09:57 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/mutations/task_mutations.py
> +    task = await ExtensionsExecutor.execute(
GraphQL already handles exceptions and shows the error message in the returned error data, which UI shows in a pop up. It helps debug issues, instead of just hiding them behind a dumb message that an error has occurred.

2024-08-20 10:42 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/inputs.py
> +    params: List[List[str]]
This change makes more sense, I'm happy to do that.

2024-08-20 11:22 UTC, jatinriverlane commented on aqueductcore/backend/models/task.py
> +class TaskCreate(TaskBase):
Sure, fine for now. I'll create a PR mentioning few refactorings we need.

2024-08-20 11:23 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/mutations/task_mutations.py
> +    task = await ExtensionsExecutor.execute(
Sure, makes sense. Thanks Amir

2024-08-20 11:27 UTC, jatinriverlane approved these changes
Thanks for addressing comments Amir

2024-08-20 15:27 UTC, samiralavi commented on aqueductcore/backend/main.py
> +        # ignore if tables already exist
After we increased the number of threads from 1 to 4 when starting Aqueduct to support extensions, we forgot to fix the DB check. This is a quick solution so we don't see unnecessary error messages in the log. It didn't require its own PR.

2024-08-20 15:30 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/types.py
> +    tasks_data: List[TaskData] = strawberry.field(description="The list of tasks in this page")
We are using the same naming scheme as experiments, and extensions as tags. I say keep it the same for coherency.

2024-08-20 15:33 UTC, safeamiiir approved these changes

2024-08-20 15:36 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/inputs.py
> +    params: List[List[str]]
For now we keep it as it is, but in future we will fix it.

2024-08-20 15:37 UTC, merged