feat: TT-134 job list pagination
AqueductHub/aqueductcore pull request #212
Opened 2024-09-04 16:22 UTC by safeamiiir

Add pagination for the job list

2024-09-04 17:13 UTC, str-anger requested changes
Can you please give some hints on what did you do here? :)

2024-09-04 17:13 UTC, str-anger commented on aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
> +    return Tasks(tasks_data=task_nodes, total_tasks_count=len(tasks))
I assume this is a bugfix

2024-09-04 17:13 UTC, str-anger commented on aqueductcore/frontend/src/pages/JobHistoryPage/index.tsx
> +import { jobListRowsPerPageOptions } from "constants/constants";
You import something here but I feel like this something is not added? Or am I missing anything? How does this add pagination?

2024-09-04 17:16 UTC, safeamiiir commented on aqueductcore/frontend/src/pages/JobHistoryPage/index.tsx
> +import { jobListRowsPerPageOptions } from "constants/constants";
This is not adding pagination by itself, it's basically being corrected (it was mistakenly imported from a wrong constant)

2024-09-04 17:16 UTC, safeamiiir commented on aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
> +    return Tasks(tasks_data=task_nodes, total_tasks_count=len(tasks))
It actually is a bugfix as i had added pagination halfway

2024-09-05 08:55 UTC, samiralavi approved these changes

2024-09-05 12:25 UTC, str-anger approved these changes

2024-09-05 12:52 UTC, merged