Fix/tt 160 greenlet spawn missing
AqueductHub/aqueductcore pull request #219
Opened 2024-09-23 12:48 UTC by jatinriverlane

## Changes
* FIxed the non working filters for get_all_tasks GraphQL Qhery

2024-09-23 16:25 UTC, samiralavi approved these changes

2024-09-24 10:53 UTC, str-anger requested changes
Very minor change request, and I am happy to approve. Basically cleaning mypy

2024-09-24 10:53 UTC, str-anger commented on aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
> +        if str(experiment.type) != "IDType.UUID":  # type: ignore
I think you still allow `experiment` to be `None`, so this is why mypy is complaining on None.type. Probably:

```suggestion
    if filters is not None:
        experiment = filters.experiment
        if experiment is not None and experiment.type != IDType.UUID:
```

2024-09-24 10:53 UTC, str-anger commented on aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
> +        experiment_uuid=experiment.value if experiment else None,  # type: ignore
I think `experiment` is out of scope, it is not defined it you did not pass the branch of `if filters:...`. Add `experiment = None` somewhere higher to add it to the scope.

2024-09-24 10:53 UTC, str-anger commented on aqueductcore/backend/services/task_executor.py
> +        .options(selectinload(orm.Task.experiment))
I hope this does not create 2 joins =)

2024-09-25 10:42 UTC, jatinriverlane commented on aqueductcore/backend/services/task_executor.py
> +        .options(selectinload(orm.Task.experiment))
No, it's creating the joins once. The only change in the final query is that previously the joins were `left outer` and now joins are `inner`.

2024-09-25 10:44 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
> +        experiment_uuid=experiment.value if experiment else None,  # type: ignore
Sure, I've added `experiment = None` to initialise `experiment` variable in `line 33`

2024-09-26 10:09 UTC, str-anger approved these changes

2024-09-26 10:18 UTC, safeamiiir approved these changes

2024-09-26 10:18 UTC, merged