feat(task-uuid): Update identifier of Task from task_id to uuid
AqueductHub/aqueductcore pull request #230
Opened 2024-10-08 14:01 UTC by jatinriverlane

# Changes
* Made relevant changes to update `task_id` to `uuid`
* Improved `humanize_list` utility function

2024-10-08 14:49 UTC, str-anger requested changes
By itself, the PR is clean and self-descriptive.
1. I'd appreciate if you rebase on cancellation PRs to also take care of their changes.
2. I'd appreciate to see a migration script as well.

2024-10-11 11:31 UTC, str-anger requested changes
Apart from comments inline, I think class `task.py/TaskProcessExecutionResult` also deserves field renaming. Can you please do this, and propagate this rename to the usage (i.e. method `_update_task_info`)

2024-10-11 11:31 UTC, str-anger commented on aqueductcore/backend/services/task_executor.py
>          select(orm.Task)
I cannot comment to line 201, but I assume it needs to be `AsyncResult(db_task.uuid).revoke(terminate=terminate, signal="SIGINT")`

Same for line 202:
`task_info = await _update_task_info(task_id=db_task.uuid, wait=False)`

2024-10-11 11:47 UTC, jatinriverlane commented on aqueductcore/backend/services/task_executor.py
>          select(orm.Task)
Oops, this change was brought by the rebase. Fixed it, thanks.

2024-10-11 13:15 UTC, str-anger approved these changes
Conditional approve, class `TaskProcessExecutionResult` may also benefit from renaming of the field.

2024-10-11 16:34 UTC, safeamiiir commented
I found some changes which are missed in the `tests/integration/test_graphql_tasks.py` file:
like lines: `43`, `57`, `88`, ...
I guess they also need to be modified, right?

2024-10-14 09:31 UTC, safeamiiir approved these changes

2024-10-14 09:41 UTC, merged