feat(delete_experiment): add feature to delete experiment
AqueductHub/aqueductcore pull request #28
Opened 2024-03-13 17:23 UTC by jatinriverlane

# Delete Experiment Feature
Allows users to delete experiments along with their linked files

## ⚠️  Breaking Changes
There are no breaking changes in this PR

## ✔️ Checklist
- [x] **Code Review**: I have reviewed my changes to ensure they meet the project's coding standards and guidelines.
- [x] **Sanity Checks**:  I have performed basic sanity checks to verify the correctness of my changes.
- [x] **Testing**: Tests have been added or updated to cover the changes made in this pull request, and all tests passed successfully.
- [x] **Style Guidelines**: My code follows the style guidelines of this project

2024-03-14 18:16 UTC, safeamiiir approved these changes
We're removing files, experiment tags and experiment record.
That's all we need to do I guess.
Thanks Jatin!

2024-03-15 09:55 UTC, samiralavi requested changes
Thanks @jatinriverlane for this work. I have requested minor but important changes. Also, the tests don't have enough assertions to check if the experiment is removed properly.

2024-03-15 09:55 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/mutations_schema.py
> +    ) -> GenericResponse:
The return type here is redundant and it can be `None`. In a scenario where an exception is raised in this function, graphql returns the error message in the `error["details"]` field. The return will succeed only when the experiment removal is done correctly (for example after checking permissions) and in that case, there is no need to return anything to the user. Please set the return type to `None` and remove the `GenericResponse` type totally to simplify the process.

2024-03-15 09:55 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/types.py
> +class GenericResponse:
This is not needed.

2024-03-15 09:55 UTC, samiralavi commented on aqueductcore/backend/services/experiment.py
> +        if os.path.exists(folder_path):
This is slow and not safe as multiple steps are happening, which should be atomic. Please use `[shutil.rmtree()](http://docs.python.org/library/shutil.html#shutil.rmtree)` to remove the experiment directory in a single call (although it uses `os.remove` internally but it is optimised by the community). You might need to check if the directory exists, but a simpler approach is to pass `ignore_errors=True` so if the directory doesn't exist, it won't fail.

2024-03-15 09:55 UTC, samiralavi commented on tests/unittests/test_graphql_mutations.py
> +    assert resp.errors is None
The assertions are not enough, you need to check if the files are actually getting removed along side the experiment in the database.

2024-03-18 10:51 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/mutations_schema.py
> +    ) -> GenericResponse:
@samiralavi We would need to have some type in response as strawberry expects some strawberry field in response. On setting None as response type, it's throwing this error as well
```Field 'removeExperiment' must not have a selection since type 'Void' has no subfields.```

2024-03-18 10:52 UTC, jatinriverlane commented on aqueductcore/backend/services/experiment.py
> +        if os.path.exists(folder_path):
@samiralavi This would be a very good and fast way, I've updated it to delete folder and it's files using shutil.rmtree

2024-03-18 10:52 UTC, jatinriverlane commented on tests/unittests/test_experiment_services.py
> +    with pytest.raises(AQDDBExperimentNonExisting):
Have updated tests to confirm deletion of folder as well in this test, thanks Amir

2024-03-18 10:52 UTC, jatinriverlane commented on tests/unittests/test_graphql_mutations.py
> +    assert resp.errors is None
Have updated tests to confirm deletion of folder as well in this test, thanks Amir

2024-03-19 11:20 UTC, samiralavi approved these changes
Thanks @jatinriverlane for the change. I want to still insist on removing the generic response. Please see my comment and check if you see my point valid

2024-03-19 11:20 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/mutations_schema.py
> +    ) -> GenericResponse:
@jatinriverlane I now understand the point. Can you instead of `GenericResponse`, just return the ID of the experiment deleted? The current `GenericResponse` is redundant the basic contract is if the mutation doesn't fail, then it has succeeded. Duplicating the `result` in the response is redundant and might confuse API users that there is a chance that a mutation has succeeded and failed at the same time!

2024-03-19 15:04 UTC, merged