feat(tags): New mutation to add multiple tags to an experiment.
AqueductHub/aqueductcore pull request #98
Opened 2024-05-08 09:47 UTC by samiralavi

This PR adds a new mutation to add a list of tags to an experiment. The service method is changed to support that and if there are duplicate tags in the request, an error will be returned following the exception. If the tags were already assigned to an experiment, the service safely continues and adds the new tags to the database and experiment. Unit tests and integration tests are added.

2024-05-08 10:36 UTC, str-anger requested changes
Some minor suggestions and questions. In general looks good.

2024-05-08 10:36 UTC, str-anger commented on aqueductcore/backend/routers/graphql/mutations/experiment_mutations.py
> +async def add_tags_to_experiment(
Having both is, as I understand, for compatibility?

2024-05-08 10:36 UTC, str-anger commented on aqueductcore/backend/routers/graphql/inputs.py
> +    experiment_id: UUID
Is this an experiment ID? I might be mistaken, but I think we agreed on EID for "user-facing" version, and unique id (or something) for UUID.

2024-05-08 10:36 UTC, str-anger commented on aqueductcore/backend/services/experiment.py
> +    user_info: UserInfo, db_session: AsyncSession, experiment_id: UUID, tags: List[ExperimentTag]
May I suggest to loosen constraint to `Collection` or `Sequence`?

2024-05-08 10:36 UTC, str-anger commented on aqueductcore/backend/services/experiment.py
> +    new_tags = {tag.lower(): tag for tag in unique_tags}
`lower()`? Is this important? I think users may be serious about this. Also, you check uniqueness of non-lowercased tags, so you may have a key conflict, one tag will be swallowed in this generator.

2024-05-08 10:36 UTC, str-anger commented on tests/unittests/test_experiment_services.py
> +        assert item in in_db_experiment_tags
```suggestion
    in_db_experiment_tags = {tag.name for tag in in_db_experiment.tags}
    assert expected_tags.issubset(in_db_experiment_tags)
```

2024-05-08 10:36 UTC, str-anger commented on tests/unittests/test_experiment_services.py
> +    expected_tags = ["test1", "test2", "test3", experiments_data[0].tags[0].name]
```suggestion
    expected_tags = {"test1", "test2", "test3", experiments_data[0].tags[0].name}
```

2024-05-08 10:36 UTC, str-anger commented on tests/unittests/test_experiment_services.py
> +    expected_tags = ["test1", "test1"]
May I suggest to validate behaviour with `expected_tags = ["teSt1", "Test1"]`

2024-05-08 10:36 UTC, str-anger commented on tests/unittests/test_graphql_mutations.py
> +    assert resp.errors[0].message == f"Duplicate tags are not allowed in the request."
```suggestion
    assert resp.errors[0].message == "Duplicate tags are not allowed in the request."
```

2024-05-08 10:44 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/inputs.py
> +    experiment_id: UUID
@str-anger Yes, this is Experiment ID. We are using Alias (EID) for `get experiment` query. For all mutations, we are taking Experiment ID as experiment identifier.

2024-05-08 10:46 UTC, str-anger commented on aqueductcore/backend/routers/graphql/inputs.py
> +    experiment_id: UUID
I'm then still confused with naming. Is we move away from "alias", what are the names now =)

2024-05-08 10:51 UTC, jatinriverlane commented on aqueductcore/backend/routers/graphql/mutations/experiment_mutations.py
> +    context: ServerContext, experiment_tag_input: ExperimentTagsInput
Parameter `experiment_tag_input` can be renamed to `experiment_tags_input` for uniformity.

2024-05-08 10:58 UTC, jatinriverlane commented on aqueductcore/backend/services/experiment.py
> +    tag_statement = select(orm.Tag).filter(orm.Tag.key.in_(new_tags.keys())).filter()
Having second `filter` call at the end would clear filter of `orm.Tag.key.in_(new_tags.keys())`.

2024-05-08 12:02 UTC, jatinriverlane approved these changes
Thanks @samiralavi , have added a few comments.

2024-05-08 12:38 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/mutations/experiment_mutations.py
> +async def add_tags_to_experiment(
Yes, it is temporary until frontend and PyAqueduct switch to the new mutation and then we will remove the old one.

2024-05-08 12:39 UTC, samiralavi commented on aqueductcore/backend/routers/graphql/inputs.py
> +    experiment_id: UUID
@str-anger we have not yet updated the names to the new scheme. This is happening in one go in different PRs. For now, we stick to the old naming.

2024-05-08 12:45 UTC, samiralavi commented on aqueductcore/backend/services/experiment.py
> +    user_info: UserInfo, db_session: AsyncSession, experiment_id: UUID, tags: List[ExperimentTag]
I understand your point, but Pydantic when validating the argument internally does some conversion which adds overhead. The recommended approach in Pyndatic for performance is that if we know the type, it is better to `list` or `tuple`:
https://docs.pydantic.dev/latest/concepts/performance/#sequence-vs-list-or-tuple-mapping-vs-dict

2024-05-08 12:51 UTC, samiralavi commented on aqueductcore/backend/services/experiment.py
> +    new_tags = {tag.lower(): tag for tag in unique_tags}
We have already thought about this. The unique key of the tag is always the lower case. We also have another field, `name` that holds the value of the tag with the casing provided by the user for display purposes. Database operations happen based on the key. If you see the previous line we check if the user-provided tags are unique or not by `unique_tags = set(tags)`.

However, looking at it again, if the user provides the same tags with different casing, it will be problematic. I am going to fix it.

2024-05-08 12:53 UTC, samiralavi commented on aqueductcore/backend/services/experiment.py
> +    tag_statement = select(orm.Tag).filter(orm.Tag.key.in_(new_tags.keys())).filter()
You are right I have missed that. The logic here has become complicated, I am trying to simplify it further.

2024-05-08 14:37 UTC, samiralavi commented
@str-anger I have pushed changes to address the bug you found along with other suggestions. Please review it and resolve the ones you believe are fine.

2024-05-09 09:33 UTC, str-anger approved these changes
There are some suggestions, optional to implement

2024-05-09 09:33 UTC, str-anger commented on .github/workflows/license_report.yml
> -
Anything related? Or just cleanup?

2024-05-09 09:33 UTC, str-anger commented on aqueductcore/backend/services/experiment.py
> +            del new_tags[db_tag.key]
Just wondering, I think this is not tooo serious, but if we allow to "add" an existing tag, should we keep the old one, or should we update the value?

2024-05-09 09:33 UTC, str-anger commented on aqueductcore/backend/services/experiment.py
> +        db_experiment.tags.append(db_tag)
I think these two loops (401 and 408) are basically performing 2 upsert (insert + update) calls: add non-existing tags and add tags to experiment. Again, I don't have a strong opinion, but to ensure atomic action you might probably benefit from sqlalchemy features, which has both native for postgres and universal support of upserts:
1. https://stackoverflow.com/questions/7165998/how-to-do-an-upsert-with-sqlalchemy
2. https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#insert-on-conflict-upsert

2024-05-09 09:33 UTC, str-anger commented on ci/unit_tests.sh
> -
I think convention suggest to have a newline in the end?

2024-05-09 09:52 UTC, samiralavi commented on .github/workflows/license_report.yml
> -
It was clean up to fix a failing workflow from prev PRs.

2024-05-09 10:00 UTC, samiralavi commented on aqueductcore/backend/services/experiment.py
> +            del new_tags[db_tag.key]
I know it is a bit ugly, but I couldn't think of a better way. An existing tag has two fields, the key and its display name. The key doesn't change as it is the lowercase of the tag name, but the decision to update the display name is something I intentionally didn't want to cover here, as there is a discussion about whether the user can change tags or not. I leave it for implemented later.

2024-05-09 10:05 UTC, samiralavi commented on aqueductcore/backend/services/experiment.py
> +        db_experiment.tags.append(db_tag)
If I understand correctly, if something fails in the session, the whole transaction including the inserts and updates is rolled back automatically by PostgreSQL. In the second response to the first link, it is mentioned that the newer version of SQLAlchemy manages that by the session. If you think this is a real problem, please let me know.

2024-05-09 10:11 UTC, samiralavi commented on ci/unit_tests.sh
> -
It is funny the line exists locally. I have just added the VSCode config to enforce it on file save.

2024-05-09 10:21 UTC, merged

2024-05-09 15:13 UTC, str-anger commented on aqueductcore/backend/services/experiment.py
> +        db_experiment.tags.append(db_tag)
It's not an issue to me, this is just relying more on database features, than self-made logic.